name: flutter_identity_manager_example
description: Demonstrates how to use the flutter_identity_manager plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  share: ^2.0.1
  flutter_identity_manager:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true