name: flutter_identity_manager
description: Manages identities in form of X509 certificates and private keys
repository: https://github.com/EPNW/flutter_identity_manager/tree/master/flutter_identity_manager
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  shared_preferences: ^2.0.6
  flutter:
    sdk: flutter
  flutter_identity_manager_platform_interface:
    git:
      url: https://github.com/EPNW/flutter_identity_manager.git
      path: flutter_identity_manager_platform_interface
  flutter_identity_manager_ios:
    git:
      url: https://github.com/EPNW/flutter_identity_manager.git
      path: flutter_identity_manager_ios
  flutter_identity_manager_android:
    git:
      url: https://github.com/EPNW/flutter_identity_manager.git
      path: flutter_identity_manager_android

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_identity_manager_android
      ios:
        default_package: flutter_identity_manager_ios
