name: flutter_identity_manager
description: Manages identities in form of X509 certificates and private keys
repository: https://github.com/EPNW/flutter_identity_manager/tree/master/flutter_identity_manager
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  shared_preferences: ^2.0.6
  flutter:
    sdk: flutter
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO: Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  flutter_identity_manager_platform_interface: #^1.0.0
    path: ../flutter_identity_manager_platform_interface
  flutter_identity_manager_android: #^1.0.0
    path: ../flutter_identity_manager_android
  flutter_identity_manager_ios: #^1.0.0
    path: ../flutter_identity_manager_ios

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_identity_manager_android
      ios:
        default_package: flutter_identity_manager_ios
